print(f"Please input your words:\n")
name = input(f"A name: ")
noun = input(f"A noun: ")
adjective = input(f"An adjective: ")
verb = input(f"A verb: ")
adjective2 = input(f"An adjective: ")
animal = input(f"An animal: ")
verb2 = input(f"A verb: ")
color = input("A color: ")
verbing = input("A verb with ing: ")
adverb = input("An adverb with ly: ")
number = input("A number: ")
measureTime = input("A measure of time: ")
color2 = input("A second color: ")
animal2 = input("A second animal: ")
number2 = input("A second number: ")
silly_word = input("A silly word: ")
noun2 = input("A 3rd noun: ")

print(f" This weekend I am going to camping with {name}. I packed my lantern, sleeping bag, and {noun}.")
print(f"I am so {adjective} to {verb} in a tent. I am {adjective2} we might see a {animal}, they are kind of dangerous.")
print(f"We are going to hike, fish, and {verb2}. I have heard that the {color} lake is great for {verbing}.")
print(f"Then we will {adverb} hike through the forest for {number} {measureTime}. If I see a {color2} {animal2} while hiking,")
print(f"I am going to bring it home as a pet! At night we will tell {number2} {silly_word} stories and roast {noun2} around the campfire!!")

